name: nlp
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - asttokens=2.0.5
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2023.05.30
  - certifi=2023.5.7
  - comm=0.1.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - executing=0.8.3
  - ipykernel=6.19.2
  - ipython=8.12.0
  - jedi=0.18.1
  - jupyter_client=8.1.0
  - jupyter_core=5.3.0
  - ld_impl_linux-64=2.38
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - libuuid=1.41.5
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - packaging=23.0
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - python=3.10.0
  - python-dateutil=2.8.2
  - pyzmq=25.0.2
  - readline=8.2
  - setuptools=67.8.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - tzdata=2023c
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
      - cachetools==4.2.4
      - chardet==3.0.4
      - charset-normalizer==3.1.0
      - google-api-core==1.34.0
      - google-auth==1.35.0
      - google-cloud-core==1.7.3
      - google-cloud-translate==2.0.1
      - googleapis-common-protos==1.59.0
      - googletrans==3.0.0
      - grpcio==1.54.2
      - grpcio-status==1.48.2
      - h11==0.9.0
      - h2==3.2.0
      - hpack==3.0.0
      - hstspreload==2023.1.1
      - httpcore==0.9.1
      - httpx==0.13.3
      - hyperframe==5.2.0
      - idna==2.10
      - protobuf==3.20.3
      - pyasn1==0.5.0
      - pyasn1-modules==0.3.0
      - pyaudio==0.2.13
      - requests==2.31.0
      - rfc3986==1.5.0
      - rsa==4.9
      - sniffio==1.3.0
      - speechrecognition==3.10.0
      - urllib3==2.0.3